### PR TITLE
chore: Run e2e in CI

### PR DESCRIPTION
**Pull request by simondotm**

### CODE REVIEW

**Comment by simondotm** [comment]
Reminds me that I should break the CI out into separate jobs for build/lint/test

**Comment by tommy9** [comment]
Doing a bit of searching around the error message, I came across mention of the X virtual frame buffer (xvfb) tool. There are a few example on GitHub https://github.com/search?q=ci.yml+Xvfb+path%3A%2F%5E.github%5C%2Fworkflows%5C%2F%2F&type=code&p=1 although not exactly matching. It might be as simple as prepending `xvfb-run` before the test task i.e. `xvfb-run npm run e2e`, although some of the examples do `sudo apt-get install xvfb` so perhaps that is needed too.

**Comment by simondotm** [comment]
@tommy9 great scott! It worked 🎩 🧙

**Comment by tommy9** [comment]
That's awesome! Really nice to have. I need to make more tests now 😀 

I can run the server unit tests too, will just need to clear out the copious amounts of console logging I left in for debugging purposes then will try to add to the CI.

**Pull request merged**
